author:
  name: Edgars Jaudzems
  email: jaudzems.edgars@inbox.lv
  url: www.edzhus.lv
title: Riga
opengraph:
  type: 'https://www.facebook.com/edzhus.lv'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4742213
  brandStrength: 1
  lightness: 0.8662727
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.4785177
typography_spectrum: 1
layout_spectrum: 0.2056928
navigation:
  - name: Edzhus Riga
    id: 3fb42ba2-2d21-4b6b-8ce4-3148dfaa724b
    type: content
name: edzhus.lv
